### ISSUE TITLE
Module name is not same with github?

### ISSUE THREAD

**Issue by donnol** [t1anz0ng/iftree#7]
```go
module github.com/TianZong48/iftree
```

github url: `https://github.com/t1anz0ng/iftree`

When I run go install: `go install github.com/t1anz0ng/iftree/cmd/iftree@latest`, it failed with:

```
go: github.com/t1anz0ng/iftree/cmd/iftree@latest: github.com/t1anz0ng/iftree@v0.0.5: parsing go.mod:
        module declares its path as: github.com/TianZong48/iftree
                but was required as: github.com/t1anz0ng/iftree
```

**Comment by t1anz0ng** [comment]
@donnol I changed my username before, will fix ASAP! Thanks

**Comment by t1anz0ng** [comment]
Fixed in https://github.com/t1anz0ng/iftree/commit/363dd82f52dc8cc2d52f29ee36386acbeb85c891 , released in https://github.com/t1anz0ng/iftree/releases/tag/v0.0.6
```shell
# go install github.com/t1anz0ng/iftree/cmd/iftree@latest
go: downloading github.com/t1anz0ng/iftree v0.0.6
```
@donnol
